import lateralRed from './lateralRed.png'
import lateralGreen from './lateralGreen.png'
import northCardinal from './northCardinal.png'
import eastCardinal from './eastCardinal.png'
import southCardinal from './southCardinal.png'
import westCardinal from './westCardinal.png'
import isolatedDanger from './isolatedDanger.png'
import emergencyWreckMarking from './emergencyWreckMarking.png'
import saveWater from './saveWater.png'
import special from './special.png'
import ship from './ship.png'
import backgroundLateral from './backgroundLateral.png'
import backgroundCardinal from './backgroundCardinal.png'

export {lateralRed, lateralGreen, northCardinal, eastCardinal, southCardinal, westCardinal, isolatedDanger, emergencyWreckMarking, saveWater, special, ship, backgroundLateral, backgroundCardinal}